name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  backend:
    name: Backend CI
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      # Install dependencies
      - name: Install backend dependencies
        working-directory: backend
        run: npm install

      # Run backend tests (if any)
      - name: Run backend tests
        working-directory: backend
        run: npm test

      # Lint backend code (optional)
      - name: Lint backend code
        working-directory: backend
        run: npm run lint || echo "Linting skipped"

  frontend:
    name: Frontend CI
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      # Install dependencies
      - name: Install frontend dependencies
        working-directory: frontend
        run: npm install

      # Build the frontend
      - name: Build frontend
        working-directory: frontend
        run: npm run build

      # Run frontend tests (if any)
      - name: Run frontend tests
        working-directory: frontend
        run: npm test

      # Lint frontend code (optional)
      - name: Lint frontend code
        working-directory: frontend
        run: npm run lint || echo "Linting skipped"