name: Deploy Portfolio and Backend

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  setup:
    runs-on: ubuntu-latest

    services:
      backend:
        image: node:20
        ports:
          - 5000:5000  # Changed port to 5000
        env:
          NODE_ENV: development
        options: >-
          --health-cmd "curl --fail http://localhost:5000 || exit 1"
          --health-interval 10s
          --health-timeout 10s  # Increased timeout
          --health-retries 5    # Increased retries

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies for backend
        working-directory: ./backend
        run: npm install

      - name: Start backend
        working-directory: ./backend
        run: |
          npm start &
          sleep 10  # Wait for the backend to start
          curl http://localhost:5000 || exit 1  # Additional check to ensure it's running
        env:
          NODE_ENV: development

      - name: Install dependencies for frontend
        working-directory: ./PortFolio
        run: npm install

      - name: Build frontend
        working-directory: ./PortFolio
        run: npm run build

      - name: Start frontend
        working-directory: ./PortFolio
        run: npm run dev
